# @format

on: [push]

jobs:
  test_one_issues:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: test_node
        run: echo '${{github.action_path}}'
      - name: install
        run: npm install
      - name: create issues
        uses: ./
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Checkout another repo
        uses: actions/checkout@v3
        with:
          repository: Jack-Zhang-1314/git-action-message
      - name: commit
        run: |
          echo '${{github.action_path}}'
          echo ${github.actor}
          git config user.name Jack-Zhang-1314
          git config user.email zyj17715640603@github.com
          git add .
          git commit -m "test json"
          git push origin main
