# @format

on: [push]

jobs:
  test_one_issues:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: install
        run: npm install
      - name: create issues
        uses: ./
        with:
          token: ${{secrets.ACTION_ACCESS}}
      - name: find json
        run: ls
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACTION_ACCESS }}
        with:
          source_file: ${{github.actor}}_test.json
          destination_repo: 'Jack-Zhang-1314/git-action-message'
          destination_folder: 'test'
          user_email: 'zyj17715640603@gmail.com'
          user_name: 'Jack-Zhang-1314'
          commit_message: 'A custom message for the commit'
      # - name: commit
      #   run: |
      #     cd ./git-action-message
      #     git config --global user.email "zyj17715640603@gmail.com"
      #     git config --global user.name  "Jack-Zhang-1314"
      #     git remote set-url origin "https://${{secrets.ACTION_ACCESS}}@github.com/Jack-Zhang-1314/git-action-message.git"
      #     git add .
      #     git commit -m "generated"
      #     git push origin main
